def create_ingredient_map():
    """Function uses a unique list of the incredients in our data and creates a mapping dictionary to simplify them."""

    return {
        "151 proof rum": "rum",
        "7-up": "soda",
        # "absinthe",
        "absolut citron": "flavored vodka",
        "absolut kurant": "flavored vodka",
        "absolut peppar": "flavored vodka",
        "absolut vodka": "vodka",
        # "advocaat",
        "agave syrup": "sugar",
        "ale": "beer",
        "allspice": "spice",
        "almond": "nut",
        "almond flavoring": "nut",
        "amaretto": "liqueur",
        "amaro montenegro": "liqueur",
        "angelica root": "herb",
        "angostura bitters": "bitters",
        "anis": "spice",
        "anise": "spice",
        "anisette": "liqueur",
        "aperol": "aperitif",
        "apfelkorn": "liqueur",
        "apple": "fruit",
        "apple brandy": "brandy",
        "apple cider": "fruit juice",
        "apple juice": "fruit juice",
        "apple schnapps": "schnapps",
        "applejack": "brandy",
        "apricot": "fruit",
        "apricot brandy": "brandy",
        "apricot nectar": "fruit juice",
        # "aquavit" ,
        "asafoetida": "spice",
        "añejo rum": "rum",
        "bacardi limon": "flavored rum",
        "baileys irish cream": "baileys",
        "banana": "fruit",
        "banana liqueur": "liqueur",
        "basil": "herb",
        # "beer",
        "benedictine": "liqueur",
        "berries": "fruit",
        "bitter lemon": "fruit",
        "bitters": "bitters",
        "black pepper": "spice",
        "black sambuca": "liqueur",
        "blackberries": "fruit",
        "blackberry brandy": "brandy",
        "blackcurrant cordial": "liqueur",
        "blackcurrant squash": "liqueur",
        "blackstrap rum": "rum",
        "blended scotch": "scotch",
        "blended whiskey": "whiskey",
        "blood orange": "fruit",
        "blue curacao": "liqueur",
        "blueberries": "fruit",
        "bourbon": "bourbon",
        "brandy": "brandy",
        "brown sugar": "sugar",
        # "butter",
        "butterscotch schnapps": "schnapps",
        # "cachaca",
        "campari": "aperitif",
        "candy": "sugar",
        "cantaloupe": "fruit",
        "caramel coloring": "sugar",
        "caramel sauce": "sugar",
        "carbonated soft drink": "soda",
        # "carbonated water",
        "cardamom": "spice",
        "carrot": "fruit",
        "cayenne pepper": "spice",
        "celery salt": "spice",
        "chambord raspberry liqueur": "liqueur",
        # "champagne",
        "cherries": "fruit",
        "cherry": "fruit",
        "cherry brandy": "brandy",
        "cherry grenadine": "sugar",
        # "cherry heering",
        "cherry juice": "fruit juice",
        "cherry liqueur": "liqueur",
        "chocolate": "sugar",
        "chocolate ice-cream": "ice cream",
        "chocolate liqueur": "liqueur",
        "chocolate milk": "milk",
        "chocolate sauce": "sugar",
        "chocolate syrup": "sugar",
        "cider": "fruit juice",
        "cinnamon": "spice",
        "cloves": "spice",
        # "club soda",
        "coca-cola": "soda",
        "cocoa powder": "spice",
        "coconut liqueur": "liqueur",
        "coconut milk": "milk",
        "coconut rum": "rum",
        "coconut syrup": "sugar",
        # "coffee",
        "coffee brandy": "brandy",
        "coffee liqueur": "liqueur",
        # "cognac",
        "cointreau": "liqueur",
        "condensed milk": "milk",
        "coriander": "spice",
        "corn syrup": "sugar",
        # "cornstarch",
        "corona": "beer",
        "cranberries": "fruit",
        "cranberry juice": "fruit juice",
        "cranberry vodka": "flavored vodka",
        "cream": "milk",
        "cream of coconut": "milk",
        "creme de banane": "liqueur",
        "creme de cacao": "liqueur",
        "creme de cassis": "liqueur",
        "creme de mure": "liqueur",
        "crown royal": "whiskey",
        "cucumber": "fruit",
        "cumin seed": "spice",
        "curacao": "liqueur",
        "daiquiri mix": "mix",
        "dark creme de cacao": "liqueur",
        "dark rum": "rum",
        "demerara sugar": "sugar",
        "dr. pepper": "soda",
        # "drambuie",
        # "dry vermouth",
        # "dubonnet rouge",
        # "egg",
        "egg white": "egg",
        "egg yolk": "egg",
        "elderflower cordial": "liqueur",
        # "erin cream",
        "espresso": "coffee",
        # "everclear",
        "falernum": "liqueur",
        "fennel seeds": "spice",
        "figs": "fruit",
        "firewater": "whiskey",
        # "food coloring" ,
        # "frangelico",
        "fresca": "soda",
        "fresh lemon juice": "fruit juice",
        "fresh lime juice": "fruit juice",
        # "fruit",
        # "fruit juice",
        "fruit punch": "fruit juice",
        # "galliano",
        # "gin",
        "ginger": "spice",
        "ginger ale": "soda",
        "ginger beer": "soda",
        "ginger syrup": "sugar",
        # "glycerine",
        "godiva liqueur": "liqueur",
        "gold rum": "rum",
        "gold tequila": "tequila",
        "goldschlager": "schnapps",
        # "grain alcohol",
        "grand marnier": "liqueur",
        "grape juice": "fruit juice",
        "grape soda": "soda",
        "grapefruit juice": "fruit juice",
        "grapes": "fruit",
        "green chartreuse": "liqueur",
        "green creme de menthe": "liqueur",
        "grenadine": "sugar",
        "guava juice": "fruit juice",
        "guinness stout": "beer",
        "half-and-half": "milk",
        "heavy cream": "milk",
        "honey": "sugar",
        "honey syrup": "sugar",
        "hot chocolate": "milk",
        "hot damn": "schnapps",
        # "hot sauce",
        "hpnotiq": "fruit juice",
        # "ice",
        "iced tea": "fruit juice",
        "irish cream": "milk",
        "irish whiskey": "whiskey",
        "islay single malt scotch": "scotch",
        "jack daniels": "whiskey",
        # "jagermeister",
        "jello": "sugar",
        "jim beam": "bourbon",
        "johnnie walker": "scotch",
        "jägermeister": "jagermeister",
        "kahlua": "liqueur",
        "kirschwasser": "brandy",
        "kiwi": "fruit",
        "kiwi liqueur": "liqueur",
        "kool-aid": "fruit juice",
        "kummel": "liqueur",
        "lager": "beer",
        "lavender": "spice",
        "lemon": "fruit",
        "lemon juice": "fruit juice",
        "lemon peel": "fruit",
        "lemon vodka": "flavored vodka",
        "lemon-lime soda": "soda",
        "lemonade": "soda",
        "licorice root": "spice",
        "light cream": "milk",
        "light rum": "rum",
        "lillet": "aperitif",
        "lillet blanc": "aperitif",
        "lime": "fruit",
        "lime juice": "fruit juice",
        "lime juice cordial": "liqueur",
        "lime peel": "fruit",
        "lime vodka": "flavored vodka",
        "limeade": "fruit juice",
        "malibu rum": "rum",
        "mango": "fruit",
        "maple syrup": "sugar",
        "maraschino cherry": "fruit",
        "maraschino liqueur": "liqueur",
        "marjoram leaves": "spice",
        "marshmallows": "sugar",
        "maui": "schnapps",
        "melon liqueur": "liqueur",
        "mezcal": "tequila",
        "midori melon liqueur": "liqueur",
        # "milk",
        "mini-snickers bars": "sugar",
        "mint": "spice",
        "mint syrup": "sugar",
        "mountain dew": "soda",
        "nutmeg": "spice",
        "olive": "fruit",
        # "olive brine",
        "orange": "fruit",
        "orange bitters": "bitters",
        "orange curacao": "liqueur",
        "orange juice": "fruit juice",
        "orange peel": "fruit",
        "orange spiral": "fruit",
        "oreo cookie": "sugar",
        "orgeat syrup": "sugard",
        "ouzo": "aperitif",
        "papaya": "fruit",
        "passion fruit juice": "fruit juice",
        "passion fruit syrup": "sugar",
        "passoa": "liqueur",
        "peach bitters": "bitters",
        "peach brandy": "brandy",
        "peach nectar": "fruit juice",
        "peach schnapps": "schnapps",
        "peach vodka": "flavored vodka",
        "peachtree schnapps": "schnapps",
        "pepper": "spice",
        "peppermint extract": "spice",
        "pepsi cola": "soda",
        # "pernod",
        "peychaud bitters": "bitters",
        "pina colada mix": "mix",
        "pineapple": "fruit",
        "pineapple juice": "fruit juice",
        "pineapple syrup": "sugar",
        "pink lemonade": "soda",
        # "pisang ambon",
        # "pisco",
        "pomegranate juice": "fruit juice",
        # "port",
        "powdered sugar": "sugar",
        # "prosecco",
        "raisins": "fruit",
        "raspberry liqueur": "liqueur",
        "raspberry syrup": "sugar",
        "raspberry vodka": "flavored vodka",
        "red chili flakes": "spice",
        # "red wine",
        # "ricard",
        "root beer": "soda",
        "rose": "spice",
        "rosemary": "spice",
        "rosemary syrup": "sugar",
        "roses sweetened lime juice": "fruit juice",
        "rosso vermouth": "vermouth",
        "ruby port": "port",
        # "rum",
        "rumple minze": "schnapps",
        "rye whiskey": "whiskey",
        "salt": "spice",
        "salted chocolate": "sugar",
        # "sambuca",
        # "sarsaparilla",
        "schweppes russchian": "soda",
        # "scotch",
        "sherbet": "sugar",
        # "sherry",
        "sirup of roses": "sugar",
        "sloe gin": "gin",
        "soda water": "carbonated water",
        "sour mix": "mix",
        "southern comfort": "whiskey",
        # "soy sauce",
        "spiced rum": "rum",
        "sprite": "soda",
        "st. germain": "liqueur",
        "strawberries": "fruit",
        "strawberry liqueur": "liqueur",
        "strawberry schnapps": "schnapps",
        # "sugar",
        "sugar syrup": "sugar",
        "surge": "soda",
        # "sweet and sour",
        "sweet vermouth": "vermouth",
        "tabasco sauce": "spice",
        "tea": "fruit juice",
        "tennessee whiskey": "whiskey",
        # "tequila",
        "thyme": "spice",
        "tia maria": "liqueur",
        "tomato juice": "fruit juice",
        # "tonic water",
        "triple sec": "liqueur",
        "tropicana": "fruit juice",
        "vanilla": "spice",
        "vanilla extract": "spice",
        "vanilla ice-cream": "milk",
        "vanilla syrup": "sugar",
        "vanilla vodka": "flavored vodka",
        # "vermouth",
        # "vodka",
        # "water",
        "watermelon": "fruit",
        "whipped cream": "milk",
        "whipping cream": "milk",
        # "whiskey",
        "whisky": "whiskey",
        "white creme de menthe": "liqueur",
        "white rum": "rum",
        "white wine": "wine",
        "wild turkey": "bourbon",
        # "wine",
        "worcestershire sauce": "spice",
        "wormwood": "spice",
        "yellow chartreuse": "liqueur",
        "yoghurt": "milk",
        "yukon jack": "whiskey",
        # "zima",
    }