CREATE TABLE all_cocktails (
    idDrink varchar CONSTRAINT PRIMARY KEY,
    strDrink varchar NOT NULL, 
    strDrinkAlternate varchar, 
    strTags varchar, 
    strVideo varchar,
    strCategory varchar, 
    strIBA varchar, 
    strAlcoholic varchar NOT NULL, 
    strGlass varchar NOT NULL, 
    strInstructions varchar NOT NULL,
    strInstructionsES varchar, 
    strInstructionsDE varchar, 
    strInstructionsFR varchar,
    strInstructionsIT varchar, 
    strInstructionsZH-HANS varchar, 
    strInstructionsZH-HANT varchar,
    strDrinkThumb varchar, 
    strIngredient1 varchar NOT NULL, 
    strIngredient2 varchar, 
    strIngredient3 varchar,
    strIngredient4 varchar, 
    strIngredient5 varchar, 
    strIngredient6 varchar, 
    strIngredient7 varchar,
    strIngredient8 varchar, 
    strIngredient9 varchar, 
    strIngredient10 varchar,
    strIngredient11 varchar, 
    strIngredient12 varchar, 
    strIngredient13 varchar,
    strIngredient14 varchar, 
    strIngredient15 varchar, 
    strMeasure1 varchar NOT NULL, 
    strMeasure2 varchar,
    strMeasure3 varchar, 
    strMeasure4 varchar, 
    strMeasure5 varchar, 
    strMeasure6 varchar,
    strMeasure7 varchar, 
    strMeasure8 varchar, 
    strMeasure9 varchar, 
    strMeasure10 varchar,
    strMeasure11 varchar, 
    strMeasure12 varchar, 
    strMeasure13 varchar, 
    strMeasure14 varchar,
    strMeasure15 varchar, 
    strImageSource varchar, 
    strImageAttribution varchar,
    strCreativeCommonsConfirmed varchar, 
    dateModified varchar NOT NULL
    );
    
CREATE INDEX drink_idx ON all_cocktails (strDrink);
