CREATE TABLE all_cocktails (
    idDrink varchar PRIMARY KEY,
    strDrink varchar NOT NULL, 
    strTags varchar, 
    strVideo varchar,
    strCategory varchar, 
    strIBA varchar, 
    strAlcoholic varchar NOT NULL, 
    strGlass varchar NOT NULL, 
    strInstructions varchar NOT NULL,
    strInstructionsDE varchar, 
    strInstructionsIT varchar, 
    strDrinkThumb varchar, 
    strIngredient1 varchar NOT NULL, 
    strIngredient2 varchar, 
    strIngredient3 varchar,
    strIngredient4 varchar, 
    strIngredient5 varchar, 
    strIngredient6 varchar, 
    strIngredient7 varchar,
    strIngredient8 varchar, 
    strIngredient9 varchar, 
    strIngredient10 varchar,
    strIngredient11 varchar, 
    strIngredient12 varchar, 
    strMeasure1 varchar NOT NULL, 
    strMeasure2 varchar,
    strMeasure3 varchar, 
    strMeasure4 varchar, 
    strMeasure5 varchar, 
    strMeasure6 varchar,
    strMeasure7 varchar, 
    strMeasure8 varchar, 
    strMeasure9 varchar, 
    strMeasure10 varchar,
    strMeasure11 varchar, 
    strMeasure12 varchar, 
    strImageSource varchar, 
    strImageAttribution varchar,
    strCreativeCommonsConfirmed varchar, 
    dateModified TIMESTAMP,
    total_ingredients int,
    strMeasure1_clean float NOT NULL,
    strMeasure2_clean float,
    strMeasure3_clean float,
    strMeasure4_clean float,
    strMeasure5_clean float,
    strMeasure6_clean float,
    strMeasure7_clean float,
    strMeasure8_clean float,
    strMeasure9_clean float,
    strMeasure10_clean float,
    strMeasure11_clean float,
    strMeasure12_clean float
    );
    

